In [5]:
# 2.2 数据操作

In [6]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.6.0


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [7]:
x = torch.empty(5, 3)
print(x)

tensor([[4.4284e-31, 8.5339e-43, 4.4283e-31],
        [8.5339e-43, 4.4284e-31, 8.5339e-43],
        [4.4284e-31, 8.5339e-43, 4.4282e-31],
        [8.5339e-43, 4.4282e-31, 8.5339e-43],
        [4.4285e-31, 8.5339e-43, 4.4285e-31]])


创建一个5x3的随机初始化的`Tensor`:



In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [11]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1390, -2.4076, -0.0041],
        [ 1.1068, -0.3039, -0.1973],
        [-0.1171, -0.3840,  0.3234],
        [ 0.4797,  0.2655, -0.9247],
        [ 0.1002,  1.1313, -0.2387]])


* **加法形式二**

In [9]:
print(torch.add(x, y))

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1390, -2.4076, -0.0041],
        [ 1.1068, -0.3039, -0.1973],
        [-0.1171, -0.3840,  0.3234],
        [ 0.4797,  0.2655, -0.9247],
        [ 0.1002,  1.1313, -0.2387]])


* **加法形式三、inplace**

In [18]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.0145, -5.0802, -0.0354],
        [ 1.6056, -0.8272, -0.4487],
        [-1.1726, -0.9432,  0.2037],
        [ 0.3162,  0.0150, -2.0129],
        [ 0.1047,  1.3641, -1.0589]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [20]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([ 2.8756, -0.6726,  1.9687])
tensor([ 2.8756, -0.6726,  1.9687])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [22]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [24]:
x += 1
print(x)
print(y) # 也加了1

tensor([[4.8756, 1.3274, 3.9687],
        [2.4988, 1.4767, 1.7485],
        [0.9445, 1.4407, 1.8803],
        [1.8365, 1.7495, 0.9118],
        [2.0044, 2.2328, 1.1799]])
tensor([4.8756, 1.3274, 3.9687, 2.4988, 1.4767, 1.7485, 0.9445, 1.4407, 1.8803,
        1.8365, 1.7495, 0.9118, 2.0044, 2.2328, 1.1799])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [26]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 2.8756, -0.6726,  1.9687],
        [ 0.4988, -0.5233, -0.2515],
        [-1.0555, -0.5593, -0.1197],
        [-0.1635, -0.2505, -1.0882],
        [ 0.0044,  0.2328, -0.8201]])
tensor([ 3.8756,  0.3274,  2.9687,  1.4988,  0.4767,  0.7485, -0.0555,  0.4407,
         0.8803,  0.8365,  0.7495, -0.0882,  1.0044,  1.2328,  0.1799])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [28]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5694])
0.5694146752357483


## 2.2.3 广播机制

In [30]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [32]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [34]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [38]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)1
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [40]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [42]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [44]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型