# 4.6 GPU计算

In [1]:
!nvidia-smi # 对Linux/macOS用户有效

Sun Mar 17 16:12:15 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| 20%   40C    P5    N/A /  75W |   1213MiB /  2000MiB |     23%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [1]:
import torch
from torch import nn

print(torch.__version__)

1.8.0


## 4.6.1 计算设备

In [2]:
torch.cuda.is_available() # cuda是否可用

False

In [3]:
torch.cuda.device_count() # gpu数量

0

In [4]:
torch.cuda.current_device() # 当前设备索引, 从0开始

AssertionError: Torch not compiled with CUDA enabled

In [5]:
torch.cuda.get_device_name(0) # 返回gpu名字

AssertionError: Torch not compiled with CUDA enabled

## 4.6.2 `Tensor`的GPU计算

In [7]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [8]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x.device

device(type='cuda', index=0)

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [13]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [14]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [15]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.5574],
        [-0.3792]], device='cuda:0', grad_fn=<ThAddmmBackward>)